### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by eabait** [Slyce-Inc/SlyceMessaging#23]
Hi all

I'm getting the following exception:
``` java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
     at it.slyce.messaging.SlyceMessagingFragment.updateTimestampAtValue(SlyceMessagingFragment.java:346)
     at it.slyce.messaging.SlyceMessagingFragment.access$500(SlyceMessagingFragment.java:61)
     at it.slyce.messaging.SlyceMessagingFragment$4.run(SlyceMessagingFragment.java:250)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```
but I haven't been able to pinpoint the conditions when is thrown. Rings any bells?

Thanks in advance!!!
Esteban

**Comment by jchunchar** [comment]
@eabait: Looks like `getActivity()` is returning `null`. I can return a check on that for a quick fix and then dig into more later.

**Comment by hawkixs** [comment]
i got the same problem, the fix isnt merged already?
